version: "3"

services:

    php:
        image: wodby/php:$PHP_TAG
        container_name: "${PROJECT_NAME}_php"
        restart: always
        environment:
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./src/:/var/www/html
        depends_on:
            - composer

    composer:
        container_name: "${PROJECT_NAME}_composer"
        image: composer
        command: install
        volumes:
            - ./src:/app

    nginx:
        image: wodby/nginx:$NGINX_TAG
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        depends_on:
            - php
        environment:
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
            NGINX_SERVER_ROOT: /var/www/html/www
        volumes:
            - ./src/:/var/www/html
        labels:
            # Enable traefik for this container
            - "traefik.enable=true"

            # Route HTTP Web
            - "traefik.http.routers.${PROJECT_NAME}_http.rule=Host(`${PROJECT_LOCALHOST}`, `www.${PROJECT_BASE_URL}`, `${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_http.entrypoints=web"

            # Route HTTPS Web
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_LOCALHOST}`, `www.${PROJECT_BASE_URL}`, `${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"

            # Redirect HTTP to HTTPS
            - "traefik.http.routers.${PROJECT_NAME}_http.middlewares=${PROJECT_NAME}_https_redirect"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.permanent=true"

            # Redirect www to normal web
            - "traefik.http.routers.${PROJECT_NAME}_https.middlewares=${PROJECT_NAME}_www_redirect"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.regex=^(https?)://${PROJECT_BASE_URL}/(.*)$$"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.replacement=$${1}://www.${PROJECT_BASE_URL}/$${2}"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.permanent=true"

            # TLS Certificates
            - "traefik.http.routers.${PROJECT_NAME}_https.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls.certresolver=myresolver"
